apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-argocd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-argocd-app
  template:
    metadata:
      labels:
        app: my-argocd-app
    spec:
      containers:
      - name: my-argocd-app
        image: srinu298/my-argocd-app:v1
        ports:
        - containerPort: 8080
